version: '3.8'

services:
  app:
    build: .
    container_name: cardapio_bot
    restart: always
    volumes:
      - ./app.log:/usr/src/app/app.log # Opcional: persistência do log
    command: python ./api.py